Update: deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,7 +26,10 @@ jobs:
       run: npm install
 
     - name: Run build
-      run: npm run build
+      env:
+        TS_NODE_PROJECT: ./tsconfig.json
+      run: |
+        npm run build || (echo "TypeScript errors detected" && exit 2)
 
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
